Repository mengxi-ream/read-frog, pull requests merged in 2025-06, with the labels that each got.

#97 perf: add request queue without retry mechanism
  .changeset/easy-trees-count.md
  src/utils/request/__test__/priority-queue.test.ts
  src/utils/request/__test__/request-queue.test.ts
  src/utils/request/priority-queue.ts
  src/utils/request/request-queue.ts
Labels: perf

#99 feat: retry and timeout mechanism of request queue
  .changeset/little-owls-work.md
  src/utils/request/__test__/request-queue.test.ts
  src/utils/request/request-queue.ts
Labels: feat

#115 fix: translate to zh-TW when user select cmn-Hant
  .changeset/little-flies-refuse.md
  src/types/config/languages.ts
  src/utils/host/__test__/free-api.test.ts
Labels: fix

#130 refactor: add shadow root for error ui
  .changeset/clean-foxes-tan.md
  .github/workflows/release.yml
  README.md
  docs/ollama/HowToUseReadFrogWithOllama.md
  src/components/api-config-warning.tsx
  src/components/tranlation-error/index.tsx
  src/components/tranlation-error/retry-button.tsx
  src/entrypoints/background/index.ts
  src/entrypoints/options/app-sidebar/index.tsx
  src/entrypoints/popup/components/quick-links.tsx
  src/utils/constants/dom-labels.ts
  src/utils/constants/dom-tags.ts
  src/utils/constants/site.ts
  src/utils/host/__test__/translate.test.tsx
  src/utils/host/dom/filter.ts
  src/utils/host/dom/traversal.ts
  src/utils/host/translate/node-manipulation.ts
  src/utils/react-shadow-host/create-shadow-host.tsx
  src/utils/react-shadow-host/css-registry.ts
  src/utils/react-shadow-host/shadow-host-builder.ts
  src/utils/render-react-component.tsx
Labels: refactor

#134 style: update translation error button style
  .changeset/bright-carrots-invent.md
  package.json
  pnpm-lock.yaml
  src/components/tranlation-error/error-button.tsx
  src/components/tranlation-error/retry-button.tsx
  src/components/ui/alert.tsx
  src/components/ui/hover-card.tsx
  src/components/ui/select.tsx
  src/components/ui/tooltip.tsx
  src/utils/react-shadow-host/shadow-host-builder.ts
Labels: style

#133 fix: flicker of the always translate switch
  .changeset/slow-turkeys-speak.md
  src/entrypoints/popup/atom.ts
  src/entrypoints/popup/components/always-translate.tsx
  src/entrypoints/popup/main.tsx
Labels: fix

#138 ci: release multiple package
  .changeset/shaggy-pumas-reply.md
  .github/workflows/release.yml
Labels: ci

#143 docs(readme): shield and title
  README.md
  README.zh-CN.md
  docs/star.png
  docs/wechat.JPG
Labels: docs

#146 fix: set target language right after entering guide step 1
  .changeset/calm-flowers-pay.md
  apps/extension/src/entrypoints/guide.content/index.tsx
  apps/extension/src/entrypoints/options/main.tsx
  apps/extension/src/entrypoints/side.content/index.tsx
  apps/extension/src/utils/atoms/storage-adapter.ts
Labels: fix

#149 refactor: translation control and fix load config
  .changeset/calm-friends-ring.md
  .changeset/fast-carrots-sell.md
  .gitignore
  apps/extension/src/entrypoints/background/config.ts
  apps/extension/src/entrypoints/host.content/index.tsx
  apps/extension/src/entrypoints/host.content/translation-control/node-translation.ts
  apps/extension/src/entrypoints/host.content/translation-control/page-translation.ts
  apps/extension/src/entrypoints/host.content/translation-trigger/index.ts
  apps/extension/src/utils/config/config.ts
  apps/extension/src/utils/config/init.ts
Labels: refactor

#156 feat: markdown file export
  .changeset/spotty-sheep-peel.md
  apps/extension/package.json
  apps/extension/src/entrypoints/side.content/components/side-content/content.tsx
  apps/extension/src/entrypoints/side.content/components/side-content/top-bar.tsx
  apps/extension/src/entrypoints/side.content/utils/downloader.ts
  apps/extension/src/locales/en.yml
  apps/extension/src/locales/ja.yml
  apps/extension/src/locales/zh-CN.yml
  apps/extension/src/locales/zh-TW.yml
  apps/extension/src/types/content.ts
  apps/extension/src/utils/constants/side.ts
  apps/website/src/app/[locale]/guide/step-1/page.tsx
  apps/website/src/app/[locale]/guide/step-2/page.tsx
  apps/website/src/app/[locale]/guide/step-3/page.tsx
  apps/website/src/app/[locale]/guide/step-4/page.tsx
  pnpm-lock.yaml
Labels: feat

#165 feat: reset config button
  .changeset/yummy-dots-turn.md
  apps/extension/src/entrypoints/options/pages/general/index.tsx
  apps/extension/src/entrypoints/options/pages/general/reset-config.tsx
  apps/extension/src/locales/en.yml
  apps/extension/src/locales/ja.yml
  apps/extension/src/locales/ko.yml
  apps/extension/src/locales/zh-CN.yml
  apps/extension/src/locales/zh-TW.yml
Labels: feat

#175 fix: use customModel if isCustomModel is true
  .changeset/polite-moles-care.md
  apps/extension/src/utils/host/translate/translate-text.ts
Labels: fix
