Repository mengxi-ream/read-frog, pull requests merged in 2025-08, with the labels that each got.

#219 fix: fix style issue for step 2 and 3
  .changeset/salty-seas-smell.md
  apps/website/src/app/[locale]/guide/step-1/page.tsx
  apps/website/src/app/[locale]/guide/step-2/page.tsx
  apps/website/src/app/[locale]/guide/step-3/page.tsx
  apps/website/src/app/[locale]/guide/step-4/page.tsx
Labels: fix

#220 style: use iconify and extract packages
  .changeset/small-friends-marry.md
  apps/extension/package.json
  apps/extension/src/components/tranlation/error/error-button.tsx
  apps/extension/src/utils/os.ts
  apps/website/next.config.mjs
  apps/website/package.json
  apps/website/source.config.ts
  apps/website/src/app/[locale]/tutorial/layout.tsx
  apps/website/tsconfig.json
  apps/website/turbo.json
  package.json
  packages/db/package.json
  packages/db/src/client.ts
  packages/db/tsconfig.json
  packages/db/tsup.config.ts
  packages/eslint-config/base.js
  packages/eslint-config/db.js
  packages/eslint-config/eslint.config.mjs
  packages/eslint-config/extension.js
  packages/eslint-config/next.js
  packages/eslint-config/package.json
  packages/eslint-config/react.js
  packages/typescript-config/backend.json
  packages/typescript-config/base.json
  packages/typescript-config/eslint.config.mjs
  packages/typescript-config/library.json
  packages/typescript-config/next.json
  packages/typescript-config/package.json
  packages/typescript-config/react.json
  pnpm-lock.yaml
Labels: style

#224 build: upgrade pnpm to 10.14
  eslint.config.mjs
  package.json
  packages/eslint-config/package.json
  pnpm-lock.yaml
Labels: build

#228 style: change lucide to iconify
  .changeset/real-nights-fry.md
  apps/extension/package.json
  apps/extension/src/components/tranlation/error/retry-button.tsx
  apps/extension/src/components/ui/checkbox.tsx
  apps/extension/src/components/ui/select.tsx
  apps/extension/src/components/ui/sheet.tsx
  apps/extension/src/components/ui/sidebar.tsx
  apps/extension/src/entrypoints/options/app-sidebar/index.tsx
  apps/extension/src/entrypoints/options/app-sidebar/nav-items.ts
  apps/extension/src/entrypoints/options/components/set-api-key-warning.tsx
  apps/extension/src/entrypoints/options/pages/api-providers.tsx
  apps/extension/src/entrypoints/options/pages/translation/always-translate.tsx
  apps/extension/src/entrypoints/options/pages/translation/personalized-prompt.tsx
  apps/extension/src/entrypoints/popup/app.tsx
  apps/extension/src/entrypoints/popup/components/language-options-selector.tsx
  apps/extension/src/entrypoints/popup/components/read-provider-selector.tsx
  apps/extension/src/entrypoints/popup/components/translate-prompt-selector.tsx
  apps/extension/src/entrypoints/popup/components/translate-provider-selector.tsx
  apps/extension/src/entrypoints/selection.content/selection-tooltip/translate-button.tsx
  apps/extension/src/entrypoints/side.content/components/floating-button/components/hidden-button.tsx
  apps/extension/src/entrypoints/side.content/components/floating-button/floating-read-button.tsx
  apps/extension/src/entrypoints/side.content/components/floating-button/index.tsx
  apps/extension/src/entrypoints/side.content/components/floating-button/translate-button.tsx
  apps/extension/src/entrypoints/side.content/components/side-content/metadata.tsx
  apps/extension/src/entrypoints/side.content/components/side-content/top-bar.tsx
  apps/extension/src/locales/en.yml
  apps/extension/src/locales/ja.yml
  apps/extension/src/locales/ko.yml
  apps/extension/src/locales/zh-CN.yml
  apps/extension/src/locales/zh-TW.yml
  apps/website/src/app/[locale]/guide/step-1/page.tsx
  apps/website/src/app/[locale]/guide/step-2/page.tsx
  apps/website/src/app/[locale]/guide/step-3/page.tsx
  apps/website/src/app/[locale]/guide/step-4/page.tsx
  apps/website/src/components/shadcn/dropdown-menu.tsx
  apps/website/src/components/shadcn/select.tsx
  pnpm-lock.yaml
Labels: style

#233 docs: update license
  LICENSE
Labels: docs

#235 fix: action env
  .github/workflows/database-migration.yml
Labels: fix

#238 docs(issues): migrate to YAML issue forms; add config links
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: docs

#239 docs: improve issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: docs

#248 docs(readme): version update
  README.md
  README.zh-CN.md
Labels: docs

#251 fix: node translation will make some node disappear
  apps/extension/src/entrypoints/options/pages/general/index.tsx
  apps/extension/src/entrypoints/side.content/components/side-content/index.tsx
  apps/extension/src/utils/host/dom/traversal.ts
  apps/extension/src/utils/host/translate/node-manipulation.ts
  apps/website/src/trpc/server.tsx
Labels: fix

#256 perf: increase translate limit
  .changeset/chilly-regions-win.md
  apps/extension/src/entrypoints/host.content/index.tsx
  apps/extension/src/entrypoints/host.content/translation-control/page-translation.ts
  apps/extension/src/utils/config/migration-scripts/v007-to-v008.ts
  apps/extension/src/utils/config/migration-scripts/v008-to-v009.ts
  apps/extension/src/utils/constants/translate.ts
Labels: perf

#268 feat: save vocab
  apps/extension/package.json
  apps/extension/src/entrypoints/background/index.ts
  apps/extension/src/entrypoints/selection.content/app.tsx
  apps/extension/src/entrypoints/selection.content/index.tsx
  apps/extension/src/entrypoints/selection.content/selection-tooltip/translate-button.tsx
  apps/extension/src/utils/constants/url.ts
  apps/extension/src/utils/message.ts
  apps/extension/src/utils/url.ts
  apps/website/package.json
  apps/website/src/app/[locale]/vocabulary/page.tsx
  apps/website/src/trpc/react.tsx
  packages/api/package.json
  packages/api/src/index.ts
  packages/api/src/router/vocabulary.ts
  packages/auth/package.json
  packages/auth/src/index.ts
  packages/auth/src/options.ts
  packages/db/migrations/0002_broad_sabra.sql
  packages/db/migrations/meta/0002_snapshot.json
  packages/db/migrations/meta/_journal.json
  packages/db/package.json
  packages/db/src/index.ts
  packages/db/src/schema.ts
  packages/db/src/schema/vocabulary.ts
  packages/definitions/eslint.config.mjs
  packages/definitions/package.json
  packages/definitions/src/constants/app.ts
  packages/definitions/src/constants/url.ts
  packages/definitions/src/index.ts
  packages/definitions/src/types/languages.ts
  pnpm-lock.yaml
Labels: feat

#271 fix: shortcut to full translate
  .changeset/calm-mugs-live.md
  apps/extension/src/entrypoints/host.content/index.tsx
Labels: fix

#275 feat: add translation style: `weakened`
  .changeset/chubby-meals-carry.md
  apps/extension/src/assets/tailwind/custom-translation-node.css
  apps/extension/src/locales/en.yml
  apps/extension/src/locales/ja.yml
  apps/extension/src/locales/ko.yml
  apps/extension/src/locales/zh-CN.yml
  apps/extension/src/locales/zh-TW.yml
  apps/extension/src/utils/constants/translation-node-style.ts
Labels: feat

#290 fix: custom prompt textarea size
  .changeset/silver-walls-pick.md
  apps/extension/src/entrypoints/options/pages/translation/personalized-prompt.tsx
Labels: fix

#299 fix: move '@import' to first line in ui themes.css
  apps/extension/package.json
  apps/extension/src/entrypoints/options/style.css
  packages/ui/src/styles/theme.css
  pnpm-lock.yaml
Labels: fix

#304 docs: update contribution guide with browser config
  apps/website/content/docs/contribution.mdx
  apps/website/content/docs/contribution.zh.mdx
Labels: docs

#306 chore: add claude md
  CLAUDE.md
Labels: chore

#305 ci: add claude code github workflow
  .github/workflows/claude-code-review.yml
  .github/workflows/claude.yml
Labels: ci

#312 fix: popup style
  .changeset/chubby-ads-count.md
  .github/workflows/claude-code-review.yml
  .github/workflows/claude.yml
  CLAUDE.md
  apps/extension/src/entrypoints/popup/app.tsx
  apps/extension/src/entrypoints/popup/components/hotkey-selector.tsx
Labels: fix

#319 perf: gemini thinking models in translation
  .changeset/little-pigs-fail.md
  .changeset/pink-geckos-strive.md
  apps/extension/package.json
  apps/extension/src/entrypoints/options/pages/api-providers.tsx
  apps/extension/src/entrypoints/options/pages/general/read-config.tsx
  apps/extension/src/entrypoints/options/pages/general/translation-config.tsx
  apps/extension/src/entrypoints/popup/components/translate-button.tsx
  apps/extension/src/entrypoints/side.content/components/floating-button/translate-button.tsx
  apps/extension/src/types/config/provider.ts
  apps/extension/src/utils/constants/config.ts
  apps/extension/src/utils/host/translate/api.ts
  packages/ui/src/components/checkbox.tsx
  pnpm-lock.yaml
Labels: perf, size:L

#321 fix: weird format when translating reddit
  .changeset/five-cows-burn.md
  apps/extension/src/utils/host/dom/style.ts
Labels: fix, app: browser extension, size:S, lgtm

#324 perf: cache auth client by proxy
  .changeset/breezy-lights-visit.md
  apps/extension/src/entrypoints/background/cache-cleanup.ts
  apps/extension/src/entrypoints/background/index.ts
  apps/extension/src/entrypoints/background/proxy-fetch.ts
  apps/extension/src/entrypoints/popup/components/language-options-selector.tsx
  apps/extension/src/types/proxy-fetch.ts
  apps/extension/src/utils/auth/auth-client.ts
  apps/extension/src/utils/config/init.ts
  apps/extension/src/utils/constants/proxy-fetch.ts
  apps/extension/src/utils/constants/url.ts
  apps/extension/src/utils/data-structure/__test__/rlu.test.ts
  apps/extension/src/utils/data-structure/rlu.ts
  apps/extension/src/utils/host/translate/api.ts
  apps/extension/src/utils/message.ts
  apps/extension/wxt.config.ts
  packages/definitions/src/constants/url.ts
  packages/eslint-config/base.js
Labels: perf, app: browser extension, size:XL

#316 docs: add contribution guide about dev
  .changeset/mighty-squids-wish.md
  apps/website/content/docs/contribution.mdx
  apps/website/content/docs/contribution.zh.mdx
Labels: docs, size:M

#330 fix: don't print floating button on web page
  .changeset/ready-schools-behave.md
  apps/extension/src/entrypoints/side.content/components/floating-button/index.tsx
Labels: fix, app: browser extension, size:XS

#337 ci: add turbo cache
  .github/workflows/database-migration.yml
  .github/workflows/pr-test.yml
  .github/workflows/release.yml
Labels: ci, size:XS

#338 chore: add dev edge script
  apps/website/package.json
  package.json
  turbo.json
Labels: chore, size:XS

#342 feat: integrate shadcn cli
  packages/ui/components.json
  packages/ui/tsconfig.json
Labels: feat, size:S, lgtm

#350 perf: redirect auth to /api/identity
  CONTRIBUTING.md
  README.md
  apps/extension/src/utils/auth/auth-client.ts
  apps/extension/src/utils/logger.ts
  apps/website/src/app/api/auth/[...all]/route.ts
  apps/website/src/app/api/identity/[...all]/route.ts
  apps/website/src/lib/auth-client.ts
  packages/api/src/trpc.ts
  packages/auth/src/options.ts
  packages/definitions/src/constants/auth.ts
  packages/definitions/src/index.ts
Labels: perf, app: browser extension, app: website, size:L

#354 fix: better translation error ui and info
  .changeset/dirty-falcons-ask.md
  apps/extension/src/components/tranlation/error/error-button.tsx
  apps/extension/src/components/tranlation/error/index.tsx
  apps/extension/src/utils/host/translate/node-manipulation.ts
Labels: fix, app: browser extension, size:M

#356 docs: add doc about chrome extension debug
  .changeset/shaky-sloths-enter.md
  apps/website/content/docs/contribution.mdx
  apps/website/content/docs/contribution.zh.mdx
  apps/website/public/images/ignore-list.jpg
Labels: docs, app: browser extension, size:L, lgtm

#363 feat: add API providers test feature
  .changeset/every-pots-glow.md
  apps/extension/src/entrypoints/options/pages/api-providers.tsx
  apps/extension/src/locales/en.yml
  apps/extension/src/locales/ja.yml
  apps/extension/src/locales/ko.yml
  apps/extension/src/locales/zh-CN.yml
  apps/extension/src/locales/zh-TW.yml
Labels: feat, app: browser extension, size:L, lgtm

#388 test: enhance Claude Code guidance and standardize test directories
  .changeset/social-adults-learn.md
  .claude/commands/create-pr.md
  .claude/commands/fix-github-issue.md
  CLAUDE.md
  apps/extension/src/utils/data-structure/__tests__/rlu.test.ts
  apps/extension/src/utils/host/__tests__/bilingual-translate.test.tsx
  apps/extension/src/utils/host/__tests__/free-api.test.ts
  apps/extension/src/utils/host/__tests__/translation-only.test.tsx
  apps/extension/src/utils/host/dom/__tests__/filter.test.ts
  apps/extension/src/utils/host/dom/__tests__/find.test.ts
  apps/extension/src/utils/request/__tests__/priority-queue.test.ts
  apps/extension/src/utils/request/__tests__/request-queue.test.ts
Labels: test, app: browser extension, size:L

#390 fix(extension): improve floating element detection in DOM filter
  .changeset/floating-element-filter-fix.md
  .claude/commands/create-pr.md
  apps/extension/src/utils/host/__tests__/bilingual-translate.test.tsx
  apps/extension/src/utils/host/dom/filter.ts
Labels: fix, app: browser extension, size:M

#391 feat(extension): add flexible baseURL support for DeepLX providers
  .changeset/lemon-words-poke.md
  .claude/agents/validation-gates.md
  .claude/agents/website-documentation-manager.md
  .claude/settings.local.json
  .github/workflows/claude-code-review.yml
  CLAUDE.md
  apps/extension/src/utils/host/translate/api.ts
  apps/extension/src/utils/host/translate/api/__tests__/deeplx-url-builder.test.ts
  apps/extension/src/utils/host/translate/api/__tests__/free-api.test.ts
  apps/extension/src/utils/host/translate/api/ai.ts
  apps/extension/src/utils/host/translate/api/deeplx.ts
  apps/extension/src/utils/host/translate/api/google.ts
  apps/extension/src/utils/host/translate/api/index.ts
  apps/extension/src/utils/host/translate/api/microsoft.ts
  apps/website/content/docs/providers/deeplx.mdx
  apps/website/content/docs/providers/deeplx.zh.mdx
  apps/website/content/docs/providers/meta.json
  apps/website/content/docs/providers/meta.zh.json
Labels: feat, app: browser extension, app: website, size:XXL

#398 i18n(extension): update the translation of 'always translate' for options page
  .changeset/shy-rules-bathe.md
  apps/extension/src/entrypoints/options/pages/translation/always-translate.tsx
  apps/extension/src/locales/en.yml
  apps/extension/src/locales/ja.yml
  apps/extension/src/locales/ko.yml
  apps/extension/src/locales/zh-CN.yml
  apps/extension/src/locales/zh-TW.yml
Labels: feat, i18n, app: browser extension, size:M, lgtm

#403 feat(extension): support border style
  .changeset/six-spiders-sit.md
  apps/extension/src/assets/tailwind/custom-translation-node.css
  apps/extension/src/locales/en.yml
  apps/extension/src/locales/ja.yml
  apps/extension/src/locales/ko.yml
  apps/extension/src/locales/zh-CN.yml
  apps/extension/src/locales/zh-TW.yml
  apps/extension/src/utils/constants/translation-node-style.ts
Labels: feat, app: browser extension, size:S, lgtm

#407 ci: add claude code GitHub workflow
  .github/workflows/claude-code-review.yml
  .github/workflows/claude.yml
Labels: ci, size:M

#400 feat(extension): support to clear cache
  .changeset/smart-trees-tap.md
  apps/extension/src/entrypoints/background/cache-cleanup.ts
  apps/extension/src/entrypoints/background/index.ts
  apps/extension/src/entrypoints/options/pages/translation/clear-cache-config.tsx
  apps/extension/src/entrypoints/options/pages/translation/index.tsx
  apps/extension/src/locales/en.yml
  apps/extension/src/locales/ja.yml
  apps/extension/src/locales/ko.yml
  apps/extension/src/locales/zh-CN.yml
  apps/extension/src/locales/zh-TW.yml
  apps/extension/src/utils/message.ts
Labels: feat, app: browser extension, size:L, lgtm
