Repository mengxi-ream/read-frog, pull requests merged in 2025-07, with the labels that each got.

#177 feat: allow export and import custom translate prompts
  .changeset/eight-buses-brake.md
  apps/extension/src/entrypoints/options/main.tsx
  apps/extension/src/entrypoints/options/pages/translation/personalized-prompt.tsx
  apps/extension/src/entrypoints/options/utils/prompt-file.ts
  apps/extension/src/locales/en.yml
  apps/extension/src/locales/ja.yml
  apps/extension/src/locales/ko.yml
  apps/extension/src/locales/zh-CN.yml
  apps/extension/src/locales/zh-TW.yml
Labels: feat

#181 fix: improve node translation toggle logic to handle translated content
  .changeset/smart-badgers-act.md
  apps/extension/src/utils/host/__test__/translate.test.tsx
  apps/extension/src/utils/host/dom/__test__/filter.test.ts
  apps/extension/src/utils/host/dom/__test__/find.test.ts
  apps/extension/src/utils/host/dom/filter.ts
  apps/extension/src/utils/host/dom/find.ts
  apps/extension/src/utils/host/translate/node-manipulation.ts
Labels: fix

#185 feat: add login
  .changeset/cuddly-swans-exist.md
  .github/workflows/database-migration.yml
  .github/workflows/pr-test.yml
  .gitignore
  apps/extension/src/entrypoints/popup/main.tsx
  apps/extension/src/entrypoints/side.content/index.tsx
  apps/extension/src/utils/config/config.ts
  apps/extension/src/utils/db/dexie/app-db.ts
  apps/extension/turbo.json
  apps/extension/vitest.config.ts
  apps/website/content/docs/providers/ollama.mdx
  apps/website/package.json
  apps/website/src/app/[locale]/layout.tsx
  apps/website/src/app/[locale]/sign-up/page.tsx
  apps/website/src/app/api/auth/[...all]/route.ts
  apps/website/src/components/github-info.tsx
  apps/website/src/components/icons.tsx
  apps/website/src/components/layout/root-toggle.tsx
  apps/website/src/components/shadcn/button.tsx
  apps/website/src/components/ui/button.tsx
  apps/website/src/lib/auth-client.ts
  apps/website/src/server/auth/index.ts
  apps/website/src/server/auth/options.ts
  apps/website/tsconfig.json
  apps/website/turbo.json
  package.json
  packages/db/drizzle.config.ts
  packages/db/eslint.config.mjs
  packages/db/migrations/0000_useful_overlord.sql
  packages/db/migrations/meta/0000_snapshot.json
  packages/db/migrations/meta/_journal.json
  packages/db/package.json
  packages/db/src/client.ts
  packages/db/src/index.ts
  packages/db/src/schema/auth.ts
  packages/db/tsconfig.json
  packages/db/tsup.config.ts
  packages/db/turbo.json
  pnpm-lock.yaml
Labels: feat

#189 build: update rollup to 4.45.1
  apps/website/pnpm-lock.yaml
  package.json
  pnpm-lock.yaml
Labels: build

#191 feat: add selection content
  .changeset/brave-maps-rush.md
  .changeset/tidy-readers-rule.md
  .github/workflows/pr-test.yml
  .husky/pre-push
  apps/extension/src/entrypoints/selection.content/app.tsx
  apps/extension/src/entrypoints/selection.content/index.tsx
  apps/extension/src/entrypoints/side.content/index.tsx
  apps/website/src/app/[locale]/layout.config.tsx
  apps/website/src/app/[locale]/tutorial/[[...slug]]/page.tsx
  apps/website/src/env.ts
  apps/website/turbo.json
Labels: feat

#204 build: update eslint config
  apps/extension/package.json
  apps/website/package.json
  package.json
  packages/db/package.json
  packages/eslint-config/extension.js
  packages/eslint-config/next.js
  packages/eslint-config/package.json
  pnpm-lock.yaml
Labels: build

#205 fix: eslint from website
  apps/website/src/components/motion/background-boxes.tsx
  apps/website/src/components/motion/container-scroll-animation.tsx
  apps/website/src/hooks/useHasTranslation.ts
  apps/website/src/hooks/useInitTargetLanguage.ts
Labels: fix

#206 build: upgrade many packages
  apps/extension/package.json
  apps/extension/src/utils/provider.ts
  apps/website/package.json
  apps/website/src/lib/constants.ts
  packages/eslint-config/package.json
  pnpm-lock.yaml
Labels: build

#210 feat: added hot key for toggling translation
  .changeset/tasty-moose-agree.md
  apps/extension/src/entrypoints/host.content/index.tsx
  apps/extension/src/entrypoints/popup/components/translate-button.tsx
  apps/extension/src/utils/os.ts
Labels: feat

#212 style: improve translate popover ui
  apps/extension/package.json
  apps/extension/src/entrypoints/selection.content/selection-tooltip/translate-button.tsx
  apps/extension/src/entrypoints/side.content/components/side-content/metadata.tsx
  apps/extension/turbo.json
  apps/website/content/docs/contribution.mdx
  apps/website/content/docs/contribution.zh.mdx
  apps/website/package.json
  apps/website/src/env.ts
  apps/website/turbo.json
  package.json
  packages/db/eslint.config.mjs
  packages/db/package.json
  packages/db/tsup.config.ts
  packages/eslint-config/db.js
  packages/eslint-config/package.json
  packages/eslint-config/react.js
  pnpm-lock.yaml
Labels: style
